#|--------------------------------------------------------------------------------|
#|  _       _  _         _____               _  _          _    _                 |
#| | |     (_)| |       |_   _|             (_)| |        | |  (_)                |
#| | |      _ | |_  ___   | |   _ __ __   __ _ | |_  __ _ | |_  _   ___   _ __    |
#| | |     | || __|/ _ \  | |  | '_ \\ \ / /| || __|/ _` || __|| | / _ \ | '_ \   |
#| | |____ | || |_|  __/ _| |_ | | | |\ V / | || |_| (_| || |_ | || (_) || | | |  |
#| |______||_| \__|\___||_____||_| |_| \_/  |_| \__|\__,_| \__||_| \___/ |_| |_|  |
#|                                                                                |
#|                       Author-Durham QQ:1664828807                              |
#|--------------------------------------------------------------------------------|

#插件config版本
version: 1.0

#邀请码长度
CodeLength: 8

mysql:
  #是否开启mysql数据库存储
  #若关闭则使用yaml存储玩家数据
  enable: false
  #数据库服务器地址
  host: localhost
  #数据库服务器端口
  port: 3306
  #数据库用户名
  user: root
  #数据库密码
  password: 123456
  #数据库名
  database: minecraft
  #数据表名
  table: Invitation

#完成邀请后执行的指令！
#  邀请者--%inviter% 被邀请者--%player%
#  插件前缀--%prefix% 邀请者累计邀请人数--%inviter_frequency%
#  注: 当邀请事件发生时 邀请者不一定在线
#    不可使用一些如在线指令如: tp、tphere等
#    指令执行者为后台执行
Invite-Command:
  - 'tell %player% %prefix%&e是%inviter%邀请了你哦！！'
  - 'tell %player% %prefix%&e他已经邀请了%inviter_frequency%人了！'
  - 'tell %player% %prefix%&a所以我奖励你一堆泥土！！ awa'
  - 'give %player% minecraft:dirt 64'